#!/usr/bin/env python3

import sys
import os
# from twython import Twython
# from twython import TwythonAuthError, TwythonError, TwythonRateLimitError
import helpers
from analyzer import Analyzer

# TODO
def main():
    
    # twitter = Twython(os.environ.get("API_KEY"), os.environ.get("API_SECRET"))
    # user = twitter.lookup_user(screen_name=sys.argv[1].lstrip("@"))
    # if user[0]["protected"]:
    #         return None
    # tweets = twitter.get_user_timeline(screen_name=sys.argv[1], count=50)
    
    score = 0
    
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    
    tweets = helpers.get_user_timeline(sys.argv[1], count=50)
    
    anz = Analyzer(positives, negatives)
    
    # for tweet in tweets:
    #     score += anz.analyze(tweet['text'])
    
    for tweet in tweets:
        score += anz.analyze(tweet)
    
    print(score)
    

if __name__ == "__main__":
    main()